version: '3'

vars:
  PROJECT_NAME: llminfo-cli
  PYTHON_PATH: python3
  PIP_PATH: pip
  VENV_PATH: .venv

tasks:
  setup:
    desc: Setup the project with virtual environment and dependencies
    cmds:
      - 'echo "Setting up {{.PROJECT_NAME}}..."'
      - 'uv venv'
      - 'uv pip install -e ".[dev]"'
      - 'echo "Setup complete!"'
      - 'echo "Run: task run to execute the CLI tool"'

  run:
    desc: Run the llminfo CLI tool
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m llminfo_cli.main'

  run-list:
    desc: Run llminfo list models command
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m llminfo_cli.main list models'

  run-credits:
    desc: Run llminfo credits command
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m llminfo_cli.main credits'

  test:
    desc: Run all tests
    cmds:
      - 'echo "Running tests..."'
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m pytest -v'

  test-unit:
    desc: Run unit tests only
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m pytest -v -k "not integration"'

  test-integration:
    desc: Run integration tests (requires API keys)
    cmds:
      - |
        if ! command -v dotenvx &> /dev/null; then
          echo "Error: dotenvx is required but not found."
          echo "Please install dotenvx from https://dotenvx.com/"
          exit 1
        fi
        dotenvx run -f .env.test -- source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m pytest -v -m integration

  coverage:
    desc: Run tests with coverage report
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m pytest --cov=llminfo_cli --cov-report=term-missing --cov-report=html'
      - 'echo "Coverage HTML report generated in htmlcov/"'

  coverage-html:
    desc: Generate HTML coverage report and open in browser
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m pytest --cov=llminfo_cli --cov-report=html'
      - 'echo "Opening coverage report in browser..."'
      - 'python -m webbrowser htmlcov/index.html'

  lint:
    desc: Run linters (ruff check and format)
    cmds:
      - 'ruff check .'
      - 'ruff format --check .'

  lint-fix:
    desc: Run linters and fix issues
    cmds:
      - 'ruff check . --fix'
      - 'ruff format .'

  type-check:
    desc: Run type checking (mypy)
    cmds:
      - 'mypy llminfo_cli tests'

  audit:
    desc: Check for security vulnerabilities in dependencies
    cmds:
      - 'echo "Checking for security vulnerabilities..."'
      - 'source {{.VENV_PATH}}/bin/activate && pip-audit || true'

  clean:
    desc: Clean up temporary files and virtual environment
    cmds:
      - 'rm -rf {{.VENV_PATH}}/'
      - 'rm -rf venv/'
      - 'rm -rf __pycache__/'
      - 'rm -rf */__pycache__/'
      - 'rm -rf .ruff_cache/'
      - 'rm -rf .mypy_cache/'
      - 'rm -rf .pytest_cache/'
      - 'rm -rf cov_html/'
      - 'rm -rf htmlcov/'
      - 'rm -rf .coverage'
      - 'find . -type f -name "*.pyc" -delete'
      - 'find . -type d -name "__pycache__" -delete'

  install-deps:
    desc: Install dependencies only
    cmds:
      - 'uv venv'
      - 'uv pip install -e ".[dev]"'

  update-deps:
    desc: Update dependencies
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && uv pip install --upgrade -e ".[dev]"'

  build:
    desc: Build the package
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && uv pip install build'
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m build'

  build-wheel:
    desc: Build wheel distribution
    cmds:
      - 'source {{.VENV_PATH}}/bin/activate && uv pip install build'
      - 'source {{.VENV_PATH}}/bin/activate && {{.PYTHON_PATH}} -m build --wheel'

  check:
    desc: Run all checks (lint, type-check, test, coverage)
    cmds:
      - 'task: lint'
      - 'task: type-check'
      - 'task: test'
      - 'task: coverage'

  dev:
    desc: Run development setup (setup, then run tests)
    cmds:
      - 'task: setup'
      - 'task: test'

  status:
    desc: Show project status
    cmds:
      - 'echo "Project: {{.PROJECT_NAME}}"'
      - 'echo "Python: $({{.PYTHON_PATH}} --version)"'
      - 'echo "Virtual environment: $(test -d {{.VENV_PATH}} && echo ''exists'' || echo ''missing'')"'
      - 'echo "Dependencies: $(test -f pyproject.toml && echo ''available'' || echo ''missing'')"'
      - 'echo "Package: $(source {{.VENV_PATH}}/bin/activate && python -c "import llminfo_cli" 2>/dev/null && echo ''installed'' || echo ''not installed'')"'

  help:
    desc: Show available tasks
    cmds:
      - 'task --list'